//assault rifles
#include "ins2/arifl/weapon_ins2akm"
#include "ins2/arifl/weapon_ins2m16a4"
#include "ins2/arifl/weapon_ins2stg44"
#include "ins2/arifl/weapon_ins2galil"
#include "ins2/arifl/weapon_ins2asval"
#include "ins2/arifl/weapon_ins2ak12"
#include "ins2/arifl/weapon_ins2f2000"
#include "ins2/arifl/weapon_ins2l85a2"
#include "ins2/arifl/weapon_ins2ak74"
//battle rifles
#include "ins2/brifl/weapon_ins2fnfal"
#include "ins2/brifl/weapon_ins2g3a3"
#include "ins2/brifl/weapon_ins2m14ebr"
#include "ins2/brifl/weapon_ins2fg42"
//rifles
#include "ins2/rifle/weapon_ins2garand"
#include "ins2/rifle/weapon_ins2kar98k"
#include "ins2/rifle/weapon_ins2enfield"
//handguns
#include "ins2/handg/weapon_ins2usp"
#include "ins2/handg/weapon_ins2beretta"
#include "ins2/handg/weapon_ins2c96"
#include "ins2/handg/weapon_ins2m29"
#include "ins2/handg/weapon_ins2deagle"
#include "ins2/handg/weapon_ins2m1911"
#include "ins2/handg/weapon_ins2glock17"
#include "ins2/handg/weapon_ins2makarov"
#include "ins2/handg/weapon_ins2webley"
#include "ins2/handg/weapon_ins2python"
//lmgs
#include "ins2/lmg/weapon_ins2rpk"
#include "ins2/lmg/weapon_ins2m249"
#include "ins2/lmg/weapon_ins2mg42"
#include "ins2/lmg/weapon_ins2lewis"
#include "ins2/lmg/weapon_ins2m60"
//explosives/launchers
#include "ins2/explo/weapon_ins2mk2"
#include "ins2/explo/weapon_ins2rpg7"
#include "ins2/explo/weapon_ins2law"
#include "ins2/explo/weapon_ins2m2"
#include "ins2/explo/weapon_ins2stick"
#include "ins2/explo/weapon_ins2pzfaust"
#include "ins2/explo/weapon_ins2m79"
#include "ins2/explo/weapon_ins2pzschreck"
#include "ins2/explo/weapon_ins2at4"
//shotguns
#include "ins2/shotg/weapon_ins2m590"
#include "ins2/shotg/weapon_ins2m1014"
#include "ins2/shotg/weapon_ins2coach"
#include "ins2/shotg/weapon_ins2ithaca"
#include "ins2/shotg/weapon_ins2saiga12"
//smgs
#include "ins2/smg/weapon_ins2mp5k"
#include "ins2/smg/weapon_ins2ump45"
#include "ins2/smg/weapon_ins2mp40"
#include "ins2/smg/weapon_ins2ppsh41"
#include "ins2/smg/weapon_ins2l2a3"
#include "ins2/smg/weapon_ins2m1928"
#include "ins2/smg/weapon_ins2mp7"
#include "ins2/smg/weapon_ins2mp18"
//carbines
#include "ins2/carbn/weapon_ins2sks"
#include "ins2/carbn/weapon_ins2m4a1"
#include "ins2/carbn/weapon_ins2mk18"
#include "ins2/carbn/weapon_ins2aks74u"
#include "ins2/carbn/weapon_ins2c96carb"
#include "ins2/carbn/weapon_ins2m1a1para"
//melees
#include "ins2/melee/weapon_ins2kabar"
#include "ins2/melee/weapon_ins2knuckles"
#include "ins2/melee/weapon_ins2kukri"
//sniper rifles
#include "ins2/srifl/weapon_ins2dragunov"
#include "ins2/srifl/weapon_ins2mosin"
#include "ins2/srifl/weapon_ins2m40a1"
#include "ins2/srifl/weapon_ins2g43"
//Melees
#include "cs16/melee/weapon_csknife"
//Pistols and Handguns
#include "cs16/pist/weapon_csglock18"
#include "cs16/pist/weapon_usp"
#include "cs16/pist/weapon_p228"
#include "cs16/pist/weapon_fiveseven"
#include "cs16/pist/weapon_dualelites"
#include "cs16/pist/weapon_csdeagle"
//Shotguns
#include "cs16/shot/weapon_m3"
#include "cs16/shot/weapon_xm1014"
//Submachine guns
#include "cs16/smg/weapon_mac10"
#include "cs16/smg/weapon_tmp"
#include "cs16/smg/weapon_mp5navy"
#include "cs16/smg/weapon_ump45"
#include "cs16/smg/weapon_p90"
//Explosives and Equipment
#include "cs16/misc/weapon_hegrenade"
#include "cs16/misc/weapon_c4"
//Assault Rifles
#include "cs16/rifl/weapon_famas"
#include "cs16/rifl/weapon_galil"
#include "cs16/rifl/weapon_ak47"
#include "cs16/rifl/weapon_m4a1"
#include "cs16/rifl/weapon_aug"
#include "cs16/rifl/weapon_sg552"
//Sniper Rifles
#include "cs16/snip/weapon_scout"
#include "cs16/snip/weapon_awp"
#include "cs16/snip/weapon_sg550"
#include "cs16/snip/weapon_g3sg1"
//Light Machine Guns
#include "cs16/lmg/weapon_csm249"
const bool p_Customizable = true; // Needed to define custom/default ammo
// Original Cry of Fear weapons
#include "cof/melee/weapon_cofswitchblade"
#include "cof/melee/weapon_cofbranch"
#include "cof/melee/weapon_cofnightstick"
#include "cof/melee/weapon_cofaxe"
#include "cof/melee/weapon_cofsledgehammer"
#include "cof/pistols/weapon_cofglock"
#include "cof/pistols/weapon_cofp345"
#include "cof/pistols/weapon_cofrevolver"
#include "cof/pistols/weapon_cofvp70"
#include "cof/smgs/weapon_coftmp"
#include "cof/smgs/weapon_cofmp5"
#include "cof/shotguns/weapon_cofshotgun"
#include "cof/rifles/weapon_cofg43"
#include "cof/rifles/weapon_cofm16"
#include "cof/rifles/weapon_cofrifle"
#include "cof/rifles/weapon_coffamas"
#include "cof/special/weapon_cofcamera"
#include "cof/special/weapon_cofbooklaser"
// Removed from Cry of Fear
#include "cof/smgs/weapon_cofm76"
// From the "Out of it" custom campaign
#include "cof/rifles/weapon_cofak74"
// From the AoMDC campaign
#include "cof/pistols/weapon_cofdeagle"
#include "cof/pistols/weapon_cofglock18"
#include "cof/pistols/weapon_cofanaconda"
#include "cof/pistols/weapon_cofberetta"
#include "cof/pistols/weapon_cofp228"
#include "cof/melee/weapon_cofknife"
#include "cof/melee/weapon_cofhammer"
#include "cof/melee/weapon_cofspear"
#include "cof/smgs/weapon_cofmp5k"
#include "cof/smgs/weapon_cofuzi"
#include "cof/shotguns/weapon_cofbenelli"
#include "cof/rifles/weapon_cofl85"
#include "cof/special/weapon_cofgolden"